---
title: "ch9_ex2"
author: "S Zimine"
date: "7/14/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

$(1+X_1)^2 + (2-X_2)^2 =4$ is a circle with radius 2 and center (-1,2)

### a)
```{r}
radius = 2
plot(NA, NA, type = "n", xlim = c(-4, 2), ylim = c(-1, 5), asp = 1,
     xlab = "X1", ylab = "X2")
symbols(c(-1), c(2), circles = c(radius), add = TRUE,inches=FALSE)
abline(v=0,  lty="dotted")
abline(h=0,  lty="dotted")

```


###b)
```{r}
radius = 2
plot(NA, NA, type = "n", xlim = c(-4, 2), ylim = c(-1, 5), asp = 1,
     xlab = "X1", ylab = "X2")
symbols(c(-1), c(2), circles = c(radius), add = TRUE,inches=FALSE)
abline(v=0,  lty="dotted")
abline(h=0,  lty="dotted")
text(c(-1), c(2), "< 4")
text(c(-4), c(2), "> 4")
```

###c)
```{r}
radius = 2
plot(c(0, -1, 2, 3), c(0, 1, 2, 8), col = c("blue", "red", "blue", "blue"), 
    type = "p", asp = 1, xlab = "X1", ylab = "X2",pch=19)
symbols(c(-1), c(2), circles = c(radius), add = TRUE, inches = FALSE)
abline(v=0,  lty="dotted")
abline(h=0,  lty="dotted")
```

###d)
When we expand the equation in terms of quadratic terms the boudary is linear
$$(1+X_1)^2 + (2-X_2)^2 =4$$
$$1+ 2X_1 + X_1^2 + 4 - 4 X_2 + X_2^2 = 4$$
$$5+ 2X_1 + X_1^2 - 4 X_2 + X_2^2 = 4$$


