---
title: "ch9_ex3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


###a)
```{r}
x1<-c(3,2,4,1,2,4,4)
x2<-c(4,2,4,4,1,3,1)
y<-c(rep(2,4),rep(4,3))

plot(x1,x2,col=y,pch=20, asp=1)
grid()
```


####b)
The optimal boundary appears to be $0.5 - X_1  + X_2 = 0$. 
```{r}
plot(x1,x2,col=y,pch=20, asp=1)
grid()
abline(a=-0.5,b=1, lty="dashed")
```

####c)
Classify to red if $0.5 - X_1  + X_2  < 0$ 

Classify to blue if $0.5 - X_1  + X_2  >0$ 

####d)
```{r}
plot(x1,x2,col=y,pch=20,asp=1)
grid()
abline(a=-0.5,b=1, lty="dashed")
abline(a=0,b=1, lty="dotted")
abline(a=-1,b=1, lty="dotted")
```

#####e)
finding support vectors
```{r}
which(x1%in%c(2,4))
which(x2%in%c(1,2,3,4))
```
We see that support points index ix `c(2,3,5,6)` Point 7 is not a support vector

```{r}
plot(x1,x2,col=y,pch=1,asp=1)
grid()
abline(a=-0.5,b=1, lty="dashed")
points(x1[c(2,3,5,6)],x2[c(2,3,5,6)], col=y[c(2,3,5,6)], pch=20)
```

####f)
A slight movement of observation 7 (4.1) would not move a separation plane as this points lies far away of the plane

A non-optimal hyperplane is not equally distant from support vectors
####g)
```{r}
plot(x1,x2,col=y,pch=1,asp=1)
grid()
abline(a=-0.9,b=1, lty="dashed")
```

###h
```{r}
plot(x1,x2,col=y,pch=1,asp=1)
grid()
points(c(4),c(2),col=2,pch=19) #additional point

```

